CREATE TABLE `db_data_on_hd` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nama_pasien` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tgl_lahir_pasien` date DEFAULT NULL,
  `no_rm_pasien` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reg_no` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  
  `jam1` time DEFAULT NULL,
  `td1` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nadi1` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `qb1` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vena_presure1` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `uf_goal1` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `uf_reuse1` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rf_removed1` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `masalah1` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `petugas1` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,

  `jam2` time DEFAULT NULL,
  `td2` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nadi2` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `qb2` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vena_presure2` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `uf_goal2` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `uf_reuse2` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rf_removed2` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `masalah2` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `petugas2` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,

  `jam3` time DEFAULT NULL,
  `td3` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nadi3` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `qb3` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vena_presure3` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `uf_goal3` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `uf_reuse3` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rf_removed3` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `masalah3` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `petugas3` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,

  `jam4` time DEFAULT NULL,
  `td4` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nadi4` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `qb4` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vena_presure4` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `uf_goal4` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `uf_reuse4` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rf_removed4` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `masalah4` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `petugas4` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,

  `jam5` time DEFAULT NULL,
  `td5` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nadi5` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `qb5` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vena_presure5` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `uf_goal5` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `uf_reuse5` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rf_removed5` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `masalah5` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `petugas5` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,

  `treated_blood_time` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `treated_blood_volume` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dialisate` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,

  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  
  PRIMARY KEY (`id`),
  KEY `idx_reg_no` (`reg_no`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
