CREATE TABLE `db_pengkajian_hemodialisa` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nama_pasien` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tgl_lahir` date DEFAULT NULL,
  `no_rm` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reg_no` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nyeri_lokasi` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nyeri_intensitas` int(11) DEFAULT NULL,
  `keadaan_umum` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gcs_e` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gcs_v` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gcs_m` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tensi` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nadi` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `respirasi` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `suhu` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mata_anemi` tinyint(1) DEFAULT 0,
  `mata_ikterus` tinyint(1) DEFAULT 0,
  `mata_reflex_pupil` tinyint(1) DEFAULT 0,
  `mata_oedema_palpebra` tinyint(1) DEFAULT 0,
  `tht_tonsil` tinyint(1) DEFAULT 0,
  `tht_tonsil_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tht_pharing` tinyint(1) DEFAULT 0,
  `tht_pharing_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tht_lidah` tinyint(1) DEFAULT 0,
  `tht_lidah_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tht_bibir` tinyint(1) DEFAULT 0,
  `tht_bibir_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `leher_jvp` tinyint(1) DEFAULT 0,
  `leher_jvp_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `leher_pembesar_kelenjar` tinyint(1) DEFAULT 0,
  `leher_pembesar_kelenjar_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `leher_kaku_kuduk` tinyint(1) DEFAULT 0,
  `thoraks_simetris` tinyint(1) DEFAULT 0,
  `thoraks_simetris_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cardiovaskuler_s1s2` tinyint(1) DEFAULT 0,
  `cardiovaskuler_s1s2_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cardiovaskuler_murmur` tinyint(1) DEFAULT 0,
  `cardiovaskuler_murmur_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cardiovaskuler_lain_lain` tinyint(1) DEFAULT 0,
  `cardiovaskuler_lain_lain_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pulmo_suara_nafas` tinyint(1) DEFAULT 0,
  `pulmo_suara_nafas_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pulmo_ronchi` tinyint(1) DEFAULT 0,
  `pulmo_ronchi_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pulmo_wheezing` tinyint(1) DEFAULT 0,
  `pulmo_wheezing_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pulmo_lain_lain` tinyint(1) DEFAULT 0,
  `pulmo_lain_lain_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `paru_trakea_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `paru_bronkus_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `paru_bronkiolus_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `paru_alveoli_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `paru_pleura_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `paru_diafragma_keterangan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `abdomen_distensi` tinyint(1) DEFAULT 0,
  `abdomen_meteorismus` tinyint(1) DEFAULT 0,
  `abdomen_peristaltic` tinyint(1) DEFAULT 0,
  `abdomen_normal` tinyint(1) DEFAULT 0,
  `abdomen_meningkat` tinyint(1) DEFAULT 0,
  `abdomen_menurun` tinyint(1) DEFAULT 0,
  `abdomen_ascites` tinyint(1) DEFAULT 0,
  `abdomen_nyeri_tekan` tinyint(1) DEFAULT 0,
  `abdomen_nyeri_tekan_lokasi` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `abdomen_hepar` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `abdomen_lien` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `extremitas_hangat_dingin` tinyint(1) DEFAULT 0,
  `extremitas_edama` tinyint(1) DEFAULT 0,
  `extremitas_edama_lokasi` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lab_laboratorium` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lab_ekg` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lab_xray` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diagnosa_kerja` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `terapi_tindakan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `perawat_nama` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dokter_nama` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tgl_kunjungan` date DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_nama_pasien` (`nama_pasien`),
  KEY `idx_no_rm` (`no_rm`),
  KEY `idx_reg_no` (`reg_no`),
  KEY `idx_tgl_kunjungan` (`tgl_kunjungan`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

